sudo: false

language:
  - ruby

rvm:
  - "2.5"

install:
  - bundle install --without debug:development

script:
  - bundle exec rake test
  - ./run-tools.sh

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - "./cherry_picks_*"
    - "./CHANGELOG_*.md"
  file_glob: true
  skip_cleanup: true
  on:
    tags: false
    branch: autotool
