sudo: false

language:
  - ruby

rvm:
  - "2.5"

install:
  - bundle install --without debug:development

script:
  - bundle exec rake test
  - ./tools.rb setup-environment configs/katello/3.14.yaml
  - ./tools.rb cherry-picks configs/katello/3.14.yaml
  - ./tools.rb changelog configs/katello/3.14.yaml
  - ls -al

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - "./cherry_picks_*"
    - "repos/katello/**/katello/CHANGELOG.md"
  file_glob: true
  skip_cleanup: true
  on:
    tags: false
    branch: autotool
