sudo: false

language:
  - ruby

rvm:
  - "2.5"

install:
  - bundle install --without debug:development

script:
  - bundle exec rake test
  - ./tools.rb setup-environment configs/katello/3.14.yaml
  - ./tools.rb cherry-picks configs/katello/3.14.yaml
  - ./tools.rb changelog configs/katello/3.14.yaml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN
  keep_history: true
  on:
    branch: master
